### ISSUE TITLE
Is this repository code supports DJI L1 "*.LDR" file?

### ISSUE THREAD

**Issue by minooisbusy** [Tribex/LDRParser#16]
Hello. I'm Minwoo Shin.

I would like to read the flight log of the DJI L1 as a "*.LDR" file that directly stores LiDAR data.

I wonder if this repository supports reading DJI's files.
It looks like it converts it to a JSON file containing a 3D coordinate system, but is this code that can read DJI's ".LDR" file?

**Comment by JoshTheDerf** [comment]
This supports https://www.ldraw.org/ files, which are used for storing models of toy bricks, not LiDAR data. Sorry!
