### ISSUE TITLE
Current script state

### ISSUE THREAD

**Issue by le717** [Tribex/LDRParser#2]
Hey!

I am wanting to resume some work on the importer script during the next few weeks, and you know just as well as I do that eventually we will need to completely replace that script because of all the issues it has. I have two ideas for accomplishing that, and one of them involves this script here.

Basically, we would use this script for parsing it and my script would simply convert the data generated by this into mesh. Your script would remain over here, and mine over there. This would make maintenance and releases much easier, as if there were changes made over here, I would simply need to update mine with the latest version and release.

I am wondering what the current state of this script is, if it is in a good state that I could begin integrating it into my script, and if there is anything I can do to help improve this script further.

I really would like to pursue this idea, as I like it more than the alternative, rewriting everything on my side.

Thanks!

**Comment by JoshTheDerf** [comment]
@le717 I've tested this script, and actually built an almost-functioning WebGL parser/renderer, but I ran into some issues related to backface culling, which would require a sort of rewrite, since previous lines can affect later ones. MPD support would be pretty simple, but at the moment, I'm not really in a hurry to do anything with it. The amount of special cases required to render every model properly is insane.

If you plan to start soon, I can start working on this again. :3

**Comment by le717** [comment]
>  I ran into some issues related to backface culling

I'm no 3D artist (can't do a lick of anything in 3D), but that can be a pain to work with and fix. Hopefully it won't be too much work!

> MPD support would be pretty simple

That would be a :+1:. MPD models are _very_ common.

> If you plan to start soon, I can start working on this again. :3

Yes, I have a few weeks break and I've wanting to code something, so I figured I'd resume work on the importer but start up here and help you out some.

**Comment by JoshTheDerf** [comment]
@le717 I pretty much got around BFC in my renderer by disabling it completely but... well... See screenshot. I don't even know how to begin covering all the special cases. Only one part, the 1x1 brick, rendered properly. Not too sure how much needs to be dealt with in the converter or the mesh builder.
![image](https://cloud.githubusercontent.com/assets/5861371/7448821/37008acc-f257-11e4-827f-2d5828b6e740.png)

**Comment by le717** [comment]
Yea, it'll probably be best to just not support BFC unless there's someone who knows how to implement it.
