### ISSUE TITLE
Comment parsing

### ISSUE THREAD

**Issue by le717** [Tribex/LDRParser#7]
How were you planning on handling comment parsing? What all do you want to do with them, what should be filtered out, and how should they be stored?

**Comment by JoshTheDerf** [comment]
@le717 Haven't decided. When I initially wrote this I was unaware that extra relevant data was stored in comments. Any suggestions?

**Comment by le717** [comment]
The comment data is not necessarily relevant to parsing the model, but some program may have usage for it. I would say to categorize the types in an dictionary with each value an array containing the extracted comments (e.g., `!HISTORY`), but that sounds a bit complex. Maybe just continue stripping the `0` and filter out lines that begin with `//` and _maybe_ the META commands listed [here](http://www.ldraw.org/article/218/#meta) (the first few relating to the original LDRAW.EXE program) since they lose all positioning context?

**Comment by JoshTheDerf** [comment]
@le717 Filtering out lines and just stripping the zero is probably the best idea, for now, though special support for some comments, such as BFC INVERTNEXT would probably be a good idea.
