### ISSUE TITLE
Is the cache even used?

### ISSUE THREAD

**Issue by le717** [Tribex/LDRParser#8]
Noticed this while reading the code trying to comment it.

[Lines 128-136](https://github.com/Tribex/LDRParser/blob/0eb9f7456d23fd1d58f2827963e511a58f145ce9/libldrparser.py#L128-L136) checks if the part has been cached. If it hasn't, it reads and caches it. But what happens if it _is_ cached? That condition is not handled. Instead, it simply returns the `myDef` object constructed above which does not appear to be all the information needed.

Now, maybe I'm missing something, but it seems as if we only build the cache and never access it. In that case, it looks like the case needs to be handled and assign some key of `myDef` (sorry, can't figure out which) to `self.__parts[myDef["partId"]]` to take advantage of the cache.

**Comment by JoshTheDerf** [comment]
@le717 Since the parts are referred to by name, the only check needed is to see if the part is not already cached. If it is, then nothing needs to change since the partId is already referenced by name.

But yeah, the cache works fine. :)

I'll comment better next time, I prawmise. :3

**Comment by le717** [comment]
I'm not sure where then parts are being retrieved from the cache, but since it works, my question has been answered and this can be closed. :)

**Comment by JoshTheDerf** [comment]
@le717 The idea is that parts never have to be "retrieved" until parsing the output. It might make sense if you take a closer look at the output format.

All the parser has to know is that a part _is_ cached.
